url: http://www.sayangraphic.com
baseurl: ""

# Site settings
title: سایان گرافیک
email: info@sayangraphic.com
tel: 44097589 - 09102152907
description: "Description"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2d1152
  secondary: 02AEF0
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: https://www.facebook.com/pages/sayangraphiccom/1477311649211617?ref=bookmarks
  - title: instagram
    url: http://instagram.com/sayangraphic/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap